### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by tighunt** [wy182000/electron_nodejs_native_addon#1]
运行的时候，有如下的错误，请问是什么问题呢，怎么解决啊，谢谢
Uncaught Error: Could not locate the bindings file. Tried:
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\build\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\build\Debug\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\build\Release\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\out\Debug\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\Debug\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\out\Release\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\Release\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\build\default\hello.node
 → C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\compiled\7.4.0\win32\x64\hello.node
    at bindings (C:\Users\tst1002\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\hello.js:1:187)
    at Object.<anonymous> (C:\Users\tst1002\Desktop\Electron\electron_nodejs_native_addon\node_modules\hello\hello.js:7:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by ticking0** [comment]
需要有binding.gyp文件
